#!/usr/bin/env bash

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SCRIPT_PATH="$(cygpath -w "$SCRIPT_DIR/mars.ps1")"

powershell.exe -NoProfile -ExecutionPolicy Bypass -File "$SCRIPT_PATH" "$@"
